sudo: required
dist: trusty
language: python
env:
  - PYTHONPATH=../.
python:
  - 2.7
  - 3.4
install:
  - pip install -r api/config/requirements/.development.txt
  # - pip install -r app/requirements/require-dev.txt
  # - pip install coveralls
  - pip install tox-travis

# services:
#   - mongodb

# before_script:
#   - sleep 15
#   - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
  tox
  # coverage run py.test
  # coverage run --source=moscowdjango,meetup app/manage.py test

after_success:
  - coveralls
  - codeclimate-test-reporter
  - bash <(curl -s https://codecov.io/bash)
# Whitelisting branches
branches:
  only:
    - master

# Blacklisting branches
branches:
  except:
    - develop
    - feature

addons:
  code_climate:
    repo_token: 26e4c110f3f6636057d6d9940f4e7a6de21a0680f5375977d17e821e50b1c615
