version: '2'
services:
    nginx:
        container_name: 'nginx'
        build: ./conf/nginx
        links:
            - letsencrypt
            - web
        environment:
            - MY_DOMAIN_NAME=akhil.rs
            - LETSENCRYPT_PORT_80_TCP_ADDR=letsencrypt
            - LETSENCRYPT_PORT_80_TCP_PORT=80
            - LETSENCRYPT_PORT_443_TCP_ADDR=letsencrypt
            - LETSENCRYPT_PORT_443_TCP_PORT=443
            - APP_PORT_80_TCP_ADDR=web
            - APP_PORT_80_TCP_PORT=80
        mem_limit: 2g
        cpu_shares: 256
        # restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes_from:
            - letsencrypt
    letsencrypt:
        container_name: 'letsencrypt'
        image: quay.io/letsencrypt/letsencrypt:latest
        command:  bash -c "sleep 6 && certbot certonly --standalone -d akhil.rs --text --agree-tos --email akhilrs.dev@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
        entrypoint: ""
        volumes:
            - /etc/letsencrypt
            - /var/lib/letsencrypt
        ports:
            - "80"
            - "443"
        environment:
            - TERM=xterm
    web:
        container_name: 'web'
        build: ./web
        ports:
            - "80"

    dockerui:
        container_name: dockerui
        image: akhilrs/dockerui:latest
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - "9001:9000"
        expose:
          - "9001"
