version: '2'
services:
    nginx:
        build: ./conf/nginx
        links:
            - letsencrypt
            - web
        environment:
            - MY_DOMAIN_NAME=akhil.rs
        mem_limit: 2g
        cpu_shares: 256
        # restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes_from:
            - letsencrypt
    letsencrypt:
        image: quay.io/letsencrypt/letsencrypt:latest
        command:  bash -c "sleep 6 && letsencrypt certonly --standalone -d akhil.rs --text --agree-tos --email akhilrs.dev@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
        entrypoint: ""
        volumes:
            - /etc/letsencrypt
            - /var/lib/letsencrypt
        ports:
            - "80"
            - "443"
        environment:
            - TERM=xterm
    web:
        build: ./conf/app
        ports:
            - "80"
